version: '3.8'

services:
  app:
    build: .
    container_name: json-mate-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on: []
